### ISSUE TITLE
Week 3 // Tim de Roller

### ISSUE THREAD

**Issue by maggness** [cmda-bt/pt-course-20-21#106]
# Package

## Name

Tim de Roller

## Class

Tech2b

## Repo link

https://github.com/maggness/PT

## Summary

Ben deze week beetje gaan kijken naar de packages die atom te bieden heeft en de stof gelezen die er te lezen was.

## Resources used

Lessen & Github

## Any thoughts?

Was wel lekker om zo'n relaxte opdracht te hebben voor tech. Was al gek aan het worden door backend dus dit hielp heel erg.

**Comment by Vuurvos1** [comment]
Hey Tim,
Je bent lekker bezig en zie dat je lekker heb geëxperimenteerd met extentions voor Atom en de therminal. 
Je code is over het algemeen best netjes als zie ik nog een `index.js` en een `server.js` terwijl er eigenlijk niks staat in de `index.js` file, dus gooi deze weg of doe er wat mee.
En misschien zou `Docs`/`Images` een iets betere naam voor de `Extras` folder maar dat moet je zelf weten
Op deze [https://github.com/maggness/PT/wiki/codeplan](github.com/maggness/PT/wiki/codeplan) pagina werken een paar van de afbeeldingen niet, mischien iets om te fixen

Ga zo door!
