### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by jody29** [cmda-bt/pt-course-20-21#11]
# Package

## Name

Jody Lorist

## Class

Tech 2

## Repo link

https://github.com/jody29/matching_feature

## Summary

For this week i've started to explore Git and the Terminal. I already had some experience with GitHub so this wasn't that challenging for me.

I started by making a GitHub repository and linking this with Git. Making the repository wasn't that hard, but to be able to link it with Git gave me a bit of trouble. I re-watched the backend lecture to see how i could link my repository with Git. This helped me a lot.

After i connected my repository with Git, I followed the bash tutorial in the Terminal. This was relatively easy for me. However, the last 5 exercises were a bit of a challenge for me. I had to search on google for the commands that were needed to complete the exercises. Here is the code that I received after completion: am9keTI5Cg==

Finally i made the job stories and the requirements list. This didn't gave me much trouble. I think i finished this in about an hour. The only thing that gave me a bit of trouble was Markdown. I had to look up how i could make a table in markdown language.

## Resources used

https://confluence.atlassian.com/bitbucketserver/basic-git-commands-776639767.html
https://joecreager.com/learnyounode-unofficial-companion/
https://www.tablesgenerator.com/markdown_tables
https://www.cyberciti.biz/faq/linux-append-text-to-end-of-file/
https://smallbusiness.chron.com/previous-directory-mac-terminal-49989.html

## Any thoughts?

I think the homework was ok. I didn't had that much of trouble with it so far. I do like to work with the terminal for the first time. This is a bit of a challenge for me, but i always like a challenge.

**Comment by Vuurvos1** [comment]
Great start! A few small things in the repo though, the license in your `package.json` (ISC) and the `LICENSE` file (MIT) in the repo don't match check [this](https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repositor) to see how to change it easily.  I also found a `ds_store` file in your repo, these files aren't necessary for the functioning of the app so please add it to the `.gitignore`, more info on ds_store files [here](https://en.wikipedia.org/wiki/.DS_Store)
