### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by jamero7** [cmda-bt/pt-course-20-21#124]
# Package

## Name

Jamero Rigters

## Class

Tech 6

## Repo link

https://github.com/jamero7/TECH21

## Summary

I started using HTML and CSS during ‘Internetstandaarden’ and it caught my interest. Recently I made my own portfolio website which helped me get a internship. Currently I’m working on multiple small websites. I would say that I’m good at using HTML as well as CSS, but I’m not excellent. I’ve learned JS basics but I’m trying to get more into it. 

## Resources used

- School
- Books
- Internet (Stackoverflow, Mozilla MDN etc.)

**Comment by MarvinMichel** [comment]
### Hi Jamero!👋
Good to know where you stand on coding level! Are you familiar with GitHub? If you've got any questions about it or it's Markdown you know where to find me. Your Wiki is coming along fine, but try to setup the code repo too. You can add some folder structure, add the `LICENSE` and start on your `README.md`. Try to do this this week to stay on track!😊
