### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by GekkeBoyJeff** [cmda-bt/pt-course-20-21#125]
# Package

## Name

Jeffrey Ullers

## Class

Tech-5

## Repo link

https://github.com/GekkeBoyJeff/ProjectTech/

**Comment by Vuurvos1** [comment]
Hi Jeffrey, 
Je repo begint al goed vorm te krijgen alleen missen er nog wel een aantal dingen, bijvoorbeeld een `.gitignore` waar je de `node_modules` folder in zet. Om vervolgens de node modules ook echt uit de repo te halen kun je [deze post](https://stackoverflow.com/questions/50675829/remove-node-modules-from-git-in-vscode) volgen.
Ik zie ook dat je nog geen wiki heb aangemaakt dus kan hier helaas geen feedback over geven, doe dit snel en zet hier al je bevindingen en concept in
