### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by jargill21** [cmda-bt/pt-course-20-21#127]
# Package

## Name

Jarreau Gill

## Class

Tech-5A

## Repo link

https://github.com/jargill21/Bloktech.git

**Comment by Vuurvos1** [comment]
Hey Jarreau,
Je repo is nog erg leeg dus kan niet heel veel feedback geven,
Begin met een goed concept bedenken voor je app, en documenteer dit in je wiki.
Commit regelmatig zodat andere feedback kunnen geven
