### ISSUE TITLE
Week 1 

### ISSUE THREAD

**Issue by Rellor** [cmda-bt/pt-course-20-21#134]
# Package

## Name

Bas de roller

## Class

Tech-6

## Repo link

https://github.com/Rellor/project-tech

## Summary

Ik heb een concept bedacht met 5 job storys en daaruit verschillende soorten requirements. Verder ben ik voor backend gaan kijken naar NPM en heb ik alvast een mappenstructuur gemaakt.

## Resources used

De video's/uitleg van de github van school, medeleerlingen en mijn broertje.

## Any thoughts?

De tutorial is erg lastig om aan de praat te krijgen. Verder was die halvewegen gecrashed waardoor ik het niet af kon maken.

**Comment by MarvinMichel** [comment]
### Hi Bas!👋
Wat jammer dat de tutorial niet goed werkte. Had de opmerking van Shabier niet geholpen? Je Wiki ziet er goed uit! Volgens mij loop je goed op schema.

**Comment by Rellor** [comment]
Hey! Ja de opmerking had geholpen en ik kon het script runnen :) ik had
alleen een bug dat ik niet verder kon bij het verwijderen van de items. Ik
had namelijk alles weg gehaald maar toch vertelde het script mij dat ik nog
iets weg moest halen

Op ma 19 apr. 2021 10:11 schreef Marvin Sernee ***@***.***>:

**Comment by ivo-online** [comment]
Ja, die bug was ik zelf ook tegengekomen. Het script verwacht dat je specifiek één commando gebruikt, anders herkent 'ie het niet en kun je niet door. Als ik het goed herinner, had ik zelf mijn directory verwijderd met rmdir. De dir is dan weg, maar het script wilde dat ik rm had gebruikt.
