### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Shakirahadjih** [cmda-bt/pt-course-20-21#135]
# Package

## Name

Shakira Hadjih

## Class

Tech 4

## Repo link

https://github.com/Shakirahadjih/ProjectTech

**Comment by SamSlotemaker** [comment]
Probeer even in het kort te omschrijven of je ergens tegenaan gelopen bent volgende keer, dan kunnen we er misschien bij helpen :) 
probeer ook je readMe bij te houden met de belangrijke informatie over jouw project (denk aan Installatie, bronnen, packages, concept).
