### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by SalwaRingimMohammed** [cmda-bt/pt-course-20-21#136]
# Package

## Name

Salwa Ringim Mohammed

## Class

Tech6b

## Repo link

https://github.com/SalwaRingimMohammed/ProjectTech

## Summary

Ik heb geleerd om met git te werken. Ik heb een wiki clone aangemaakt. En heb het huiswerk gemaakt: job stories, concept, wireframes. Ik heb ook geprobeerd om met mijn support group de CLI tutorial te doen, maar het werkt niet. We komen er wel in, we kunnen dingen typen, maar er gebeurt niks als we de opdracht (correct) hebben uitgevoerd. We gaan niet naar de volgende vraag. We hebben het geprobeerd in vier verschillende soorten terminals (Git Bash, Node.js, Bash Terminal van Visual Code Studio en de ingebouwde terminal van onze computer). Leden van onze support group die een mac hadden konden het wel.

## Resources used

Ik heb geen externe bronnen gebruikt. Ik heb alleen gedaan wat er bij de assignments stond en heb mijn support group gevraagd om hulp als ik dat nodig had.

## Any thoughts?
Ligt het feit dat we de tutorial niet konden doen aan Git Bash of aan onze Windows laptop? Of hebben wij iets verkeerds gedaan?

**Comment by MarvinMichel** [comment]
### Hi Salwa!👋
De Wiki clone is goed gegaan, maar ik zie nog geen content. Zorg even dat je het huiswerk ook nog even daar aan toevoegt. Maak ook nog even een begin aan je file structure, dus je `README.md`, je `LICENSE` etc. De issues hoeven niet heel uitgebreid. Als je even kort uitlegt wat je gedaan hebt kunnen we wat directer kijken naar wat je werk. Als je ergens tegenaan loopt kun je dat ook altijd vermelden (of ons even een bericht sturen op Teams).

**Comment by ivo-online** [comment]
We hebben het in de les ook even gehad over het opstarten van de command line tutorial, en de instructies in de opdracht zijn inmiddels ook wat aangescherpt. Helpt dat? Als het nog steeds lukt, laat het svp even weten aan mij of de assistenten, dan helpen we je op weg!

**Comment by ivo-online** [comment]
En nu ik je issue nog een keer doorlees, vraag ik me ook af of jullie op Windows het Linux subsystem hebben geinstalleerd? Op een Mac is dat (althans iets vergelijkbaars) standaard beschikbaar, maar op Windows niet. Zie evt. de instructies op getting-started.md of ook in dit geval, laat het weten als het niet lukt!
