### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Juliusmeeuwisse** [cmda-bt/pt-course-20-21#140]
# Package

## Name

Julius Meeuwisse

## Class

Tech 4 

## Repo link

https://github.com/Juliusmeeuwisse/bloktech

## Summary

Ik heb een concept bedacht, job stories en requirements list gemaakt. Ook heb ik geschreven over Github en de terminal.

## Resources used

Week 1 wiki van project tech

## Any thoughts?

Het huiswerk was goed te doen, aan het begin lukte het me alleen niet om node helemaal goed te installeren. Elke keer als ik mijn terminal opnieuw opende werd hij gedeactiveerd maar ik heb dit later gefixed door te kijken op een aantal threads.

**Comment by SamSlotemaker** [comment]
Top dat je het zelf op hebt weten te lossen, zo ga je nog wel een aantal rare errors krijgen aankomende weken (: 
Probeer ook je readMe bij te houden met de belangrijke informatie over jouw project (denk aan Installatie, bronnen, packages, concept).
