### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by AsaMarjew** [cmda-bt/pt-course-20-21#141]
# Package

## Name

Asa Marjew

## Class

Tech 6

## Repo link

https://github.com/AsaMarjew/DatingApp2021/wiki

## Summary

Concept fase van mijn feature toegevoegd met Job story en bijbehorende requirements.

## Resources used

Github HvA CMD Block Tech

## Any thoughts?

Veel! Ik heb het nog niet af

**Comment by MarvinMichel** [comment]
### Hi Asa!👋
Hoe komt het dat je het niet af hebt gekregen? Is het teveel of loop je ergens mee vast? Stuur me even een berichtje op Teams als ik je ergens mee kan helpen!😊 Je Wiki ziet er goed uit en je hebt al een mooi begin gemaakt aan je repo structuur, dus dat ziet er tot nu toe goed uit!
