### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by AllyssaA** [cmda-bt/pt-course-20-21#153]
# Package

## Name

Allyssa

## Class

tech-5

## Repo link

https://github.com/AllyssaA/matching-app

## Summary

Concept/idee uitgewerkt met 5 job stories en 1 daarvan uitgekozen. Opdrachten van week 1 uitgevoerd.

## Resources used

https://www.cmdmethods.nl/cards/stepping-stones/requirement-list
https://jtbd.info/replacing-the-user-story-with-the-job-story-af7cdee10c27

**Comment by Vuurvos1** [comment]
Hi Allyssa,
Leuk concept en goede job stories. Begin met wireframes maken een goed beeld te krijgen hoe je app er uit gaat zien. Ook denk ik dat je je requirements wel uit kunt berijden en mischien wat specifieker maken. Je repo ziet er verder super uit, ga zo door!
(in job story 4 moet prfiel profiel zijn ;) )
