### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by jabirtisou** [cmda-bt/pt-course-20-21#154]
# Package

## Name
Jabir Tisoudali

## Class
Tech 4A

## Repo link
https://github.com/jabirtisou/CMDBlokTech

## Summary
Job stories,Requirements, Concept en interface toegevoegd.

**Comment by SamSlotemaker** [comment]
Lekker bezig, Jabir! Top dat je je readMe al enigszins ingericht hebt, blijf deze vooral aanvullen! :)
