### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by jargill21** [cmda-bt/pt-course-20-21#155]
# Github

## Name

Jarreau Gill

## Class

tech-5

## Repo link

https://github.com/jargill21/Bloktech

## Summary

ik heb de 5 Job story's gemaakt en heb daarna eentje uitgekozen en een requirementslist gemaakt.
Ik moet nog meer informatie erbij zetten.

**Comment by Vuurvos1** [comment]
Hi Jarreau,
Je job stories beginnen er al goed uit te zien, zoals je zelf al zegt mist er nog een beetje informatie in de wiki. Ga bijvoorbeeld wireframes maken om een beeld te krijgen over hoe je app er uit gaat zien.
Kijk nog even hoe je markdown schrijft, ik zie hier en daar nog wat hashtags staan die er niet hooren zie [Markdown-Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet). Lees alles nog even goed na, sommige dingen staan nu dubbel in je wiki waardoor het niet lekker leest
Verder goed bezig, ga zo door
