### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by kiara1404** [cmda-bt/pt-course-20-21#156]
# Package

## Name

Kiara 

## Class

Tech 6

## Repo link

https://github.com/kiara1404/dating_app2021

## Summary

Ik heb mijn concept kort uitgeschreven, verschillende job stories bedacht en een requirements list gemaakt.

**Comment by MarvinMichel** [comment]
## Hi Kiara!👋
Wat een super tof concept! Je job stories zijn ook heel goed geschreven. Je landing page schets mag wel iets uitgebreider. Laat zien wat je voor ogen hebt met de like knop bijvoorbeeld. Iets meer detail mag wel. Weet je ook al welke feature je uit wilt gaan werken? Zorg ook dat je je repo goed op orde hebt, dus inclusief een `README.md`, `LICENSE` etc. 
Je bent echt super goed bezig!😍

**Comment by ivo-online** [comment]
Zeker een leuk concept! Mijn tip is nog om je feature in eerste instantie niet te groot te maken. Profiel maken / wijzigen is op zich al een mooie stap, zonder ook nog te kunnen zoeken/filteren of een messenger functie. Als alles goed gaat, kun je natuurlijk altijd nog uitbreiden. Of met andere woorden: probeer requirements op te stellen voor je job story en nog niet voor het hele concept.
