### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by jamero7** [cmda-bt/pt-course-20-21#158]
# Package

## Name

Jamero Rigters

## Class

TECH6B

## Repo link

https://github.com/jamero7/TECH21

## Summary

Ik heb de informatie over open source en GitHub gelezen. Bovendien heb ik de concept fase afgerond en ben ik bezig geweest met de terminal (waar ik overigens niet helemaal uit kwam). 

## Resources used

Aangeleverde bronnen.

## Any thoughts?

Bij de terminal opdracht kwam ik niet ver. Ik heb `console.log('Hello World!');` geprobeerd, maar dit werkte niet. Googlen hielp ook niet echt.

**Comment by ivo-online** [comment]
Met de terminal opdracht kunnen docenten of assistenten je vast verder helpen! We hebben dan wel iets meer info nodig: wat probeer je precies te doen, welke foutmelding krijg je? Een screenshot doet ook vaak wonderen. Aarzel niet via Teams om hulp te vragen!
