### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by Tomvandenberg11** [cmda-bt/pt-course-20-21#160]
# Package

## Name

Tom van den Berg

## Class

Tech 6

## Repo link

https://github.com/Tomvandenberg11/ProjectTech

## Summary

Deze week ben ik begonnen met het coderen van de website met behulp van de template engine. Ik heb ejs als template engine gekozen, omdat dit het meeste overeenkomt met normale HTML. Ik heb een aantal componenten, stijl en een plaatje toegevoegd. 

## Resources used
-

## Any thoughts?

Ik denk dat het huiswerk best wel goed ging! Ik had nog wat meer elementen aan de website willen toevoegen, maar dat komt de komende weken zeker wel goed.

**Comment by MarvinMichel** [comment]
## Hi Tom!👋
EJS is prima keuze! Het wordt veel gebruikt, wat het makkelijker maakt om antwoorden te vinden als je ergens mee vastloopt. Qua styling zie ik dat je nog steeds veel met pixels werkt. Probeer over te stappen op flexibele units om je website te preppen voor responsiveness.😊
