### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by kiara1404** [cmda-bt/pt-course-20-21#161]
# Package

## Name

Kiara

## Class

Tech 6

## Repo link

https://github.com/kiara1404/dating_app2021/wiki

## Static website link
https://kiara1404.github.io/dating_app2021/static/index.html

## Summary

Ik ben begonnen in HTML en CSS om mijn static website vorm te geven.  Ik ben van plan om aankomende week deze website met ejs te bouwen. Ik vind het fijn dat ik dan al een statische website heb en mijn HTML code makkelijker kan 
 opsplitsen

## Resources used

Ik heb een ander concept dan vorig jaar maar haal wel veel hulp uit mijn oude code. 
https://github.com/kiara1404/dating_app

## Any thoughts?
-

**Comment by MarvinMichel** [comment]
## Hi Kiara!👋
Probeer inderdaad wel zo snel mogelijk over te stappen op EJS, dan kan je daar ook alvast aan wennen. Klein tip voor je code: het is niet erg als je classes gebruikt, maar geef ze een duidelijke benaming. Dat maakt je code een stuk leesbaarder. Vergeet ook niet een `README.md` toe te voegen aan je repo met een korte uitleg over je concept.
