### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by PhilipvEgmond** [cmda-bt/pt-course-20-21#164]
# Package

## Name

Philip van Egmond

## Class

Tech 6

## Repo link

https://github.com/PhilipvEgmond/Tech-6

## Summary

Ik heb een begin gemaakt aan de README. Daarnaast heb ik de Git pagina in m'n wiki geschreven en de aanpak die ik in gedachten heb toegelicht. 

## Resources used

https://chris.beams.io/posts/git-commit/
https://www.katacoda.com/courses/git

## Any thoughts?

Ik denk niet dat iedereen alle artikelen en dergelijken leest. Ik denk dat het een goed idee is om hierom in de les ook de nadruk te leggen op een goede git commit schrijven. Lijkt me belangrijk om goed te kunnen!

**Comment by MarvinMichel** [comment]
## Hi Phillip!👋
Goede feedback! Ook al is het wel de bedoeling dat de artikelen gelezen worden natuurlijk. Het is immers lesstof dat wordt aangereikt.

Ik zie ook dat je steeds dezelfde `<head>` gebruikt in je EJS templates. Misschien dat je daar nog een partial van kan maken en die kan includen op alle pagina's. Dan hoef je hem maar 1 keer te schrijven. En als je in Javascript een functie schrijft die iets returned, kan je ze 'chainen' als je dat wilt. Bij [deze regels](https://github.com/PhilipvEgmond/Tech-6/blob/b876e9a3cf81c688e915093f991db021091d3315/server.js#L7-L16) in je `server.js` bestand kun je dat bijvoorbeeld gebruiken. Dan wordt het dit:
```js
app
    .set('view engine', 'ejs')
    .use(express.static("public"))
    .use(partials())
    .get('/', home)
    .get('/about', about)
    .get('/influencer', influencer)
    .get('*', error404);
```
Is zeker geen must, maar kan je code wat cleaner maken!😊
