### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by 123rvb123** [cmda-bt/pt-course-20-21#170]
# Package

## Name
Remco van Bruggen

## Class
Tech 5

## Repo link
https://github.com/123rvb123

## Summary
Alles is tot nu toe goed gelukt. De routes aanmaken en de 404 ging een beetje moeilijk in het begin. Ik maakte een aantal foutjes in de code en daardoor deed die het steeds niet. Ik had ook een probleem met het opstarten van de server, want telkens gaf die errors aan. Ik heb het hier met Janno in de les over gehad, en ik heb het hierdoor gelukkig kunnen maken.

Helaas kwam ik niet verder met mijn template engine. Ik heb geprobeerd Pug te installeren alleen lukte dit helaas niet. Janno heeft me geholpen met handlebars, en daar ga ik nu mee aan de slag in de vakantie. 

## Resources used
https://expressjs.com/en/starter/faq.html#:~:text=In%20Express%2C%20404%20responses%20are,that%20none%20of%20them%20responded.

https://expressjs.com/en/guide/routing.html

https://expressjs.com/en/starter/basic-routing.html

## Any thoughts?

Routing was duidelijk, template engine wat moeilijker te begrijpen.

**Comment by Vuurvos1** [comment]
Hi Remco,

Je zou templating kunnen zien als het dynamisch genereren van HTML wat je dan naar de client stuurt.
De setup van handlebars is misschien wat raar in de file structuur die je aan moet houden, dus let hier op. Mocht je vast lopen met het opzetten van handlebars is [dit artiekel](https://waelyasmina.medium.com/a-guide-into-using-handlebars-with-your-express-js-application-22b944443b65) een erg goede bron.
Vergeet niet regelmatig te committen, nu is de code in je repo 15 dagen oud en kan er dus geen feedback gegeven worden op de nieuwere dingen. 
Het navigeren van je wiki gaat een beetje lastig, alle links in de sidebar linken terug naar de pt-course-20-21 wiki als je dit dus niet door hebt zit je eigenlijk in een hele andere (en lege) wiki te kijken. Update dus je sidebar dat hij naar je eigen wiki linkt en naar de paginas die je zelf nog hebt toegevoegd.
Wat je aan informatie hebt in je wiki ziet er al goed uit al kan dit nog wel wat aangedikt worden, geef bijvoorbeeld iets meer uitleg waarom je kiest voor een job story, waarom kies je voor MMA specifiek en niet voor sport in het algemeen en maak wireframes om een beter idee te krijgen hoe je app er uit gaat zien.

Verder ben je volgens mij lekker op weg dus ga zo door en houdt vooral vakantie :)
