### ISSUE TITLE
Week 3

### ISSUE THREAD

**Issue by judithkoelewijn** [cmda-bt/pt-course-20-21#171]
# Package

## Name

Judith Koelewijn

## Class

tech-5

## Repo link

https://github.com/judithkoelewijn/matching-application

## Summary

- Frontend verder gebouwd, naar drie werkende pagina's
- Markdown readme aangepast
- De hele Wiki op GitHub up to date gemaakt en bijgewerkt
- De structuur opgezet
- Linting and formatting onderzocht 
- Handlebars toegevoegd aan de frontend, combineren van back en frontend en stukje werkend gekregen met handlebars (gebruiker vult formulier in en krijgt daarna succes pagina met Hi {{naam}}
-

## Any thoughts?

Het huiswerk was goed te doen, ik heb even een stukje moeten inhalen maar eenmaal op de rit ging het best snel. Fijn hoe nu alles 'bij elkaar komt' en duidelijker wordt.

**Comment by Vuurvos1** [comment]
Hi Judith,
Let nog een beetje op je code consistentie en gebruik je linter waar kan, ik zie [hier](https://github.com/judithkoelewijn/matching-application/blob/main/matching-app.js#L74) bijvoorbeeld een random spatie en [hier](https://github.com/judithkoelewijn/matching-application/blob/main/matching-app.js#L67-L70) staan 2 enters terwijl dit haakje volgens mij nog bij het stukje code erboven hoort.
Schoon je `package.json` ook nog eens op en haal alle dependensies weg die je niet gaat gebruiken [deze](https://github.com/judithkoelewijn/matching-application/blob/main/package.json#L32-L33) bijvoorbeeld
Kwa onderzoek en documentatie zit het volgens mij wel goed, alleen vergeet niet je wireframes in je wiki aan te vullen
