### ISSUE TITLE
Week 3

### ISSUE THREAD

**Issue by Daan-Zwarthoed** [cmda-bt/pt-course-20-21#172]
# Package

## Name

Daan Zwarthoed

## Class

tech 4 B

## Repo link

https://github.com/Daan-Zwarthoed/Blok-Tech-Daan-Zwarthoed

## Summary

Ik heb deze week voor project tech scss ingevoerd in mijn project aangezien dit een hele chille manier is om css te schrijven en ik hier veel aan heb voor mijn project.
Ik heb nu wel voor elke scss file een css file dus hierdoor heb ik wel veel extra files dus hier wil ik nog wel wat op vinden.

## Resources used

https://sass-lang.com/

## Any thoughts?

-

**Comment by BVictorB** [comment]
Hi Daan, leuk dat je aan de slag bent gegaan met SCSS! Ik denk dat het misschien nuttig kan zijn voor je om even een kijkje te nemen naar mijn project van Blok Tech van vorig jaar. Hierin gebruik ik ook SCSS en ik vind zelf dat ik dit wel op een nette manier heb gedaan: [https://github.com/BVictorB/friendship](https://github.com/BVictorB/friendship)
