### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by samclarkb** [cmda-bt/pt-course-20-21#21]
# Package

## Name

Sam Boot

## Class

205

## Repo link

https://github.com/samclarkb/Blok-Tech-/wiki

## Summary

Ik ben deze week begonnen met een opfris course van javascript te volgen. Deze heb ik gevolgd op Lynda.com en deze course stond de github pagina van blok tech. ik ben t/m hoofdstuk 5 gekomen. Voor de rest heb ik het huiswerk van week 1 gemaakt wat vooral bestond uit installaties en samenvattingen schrijven.

## Resources used

De werkgroepen en dit filmpje om npm wat meer te begrijpen https://www.youtube.com/watch?v=2V1UUhBJ62Y&feature=youtu.be

## Any thoughts?

Duidelijke introductie van het blok. Er zijn een paar dingen die ik nog niet begrijp (zoals: terminal), maar ik ga er vanuit dat het me gaande weg duidelijk word. Er overheerst een gevoel van motivatie om nieuwe dingen te leren.

**Comment by MarvinMichel** [comment]
Hi Sam!
Super leuk om te horen dat je zo gemotiveerd bent! Houd die pit erin😊 Kijk of je met de terminal wat kan oefenen en als je ergens niet uitkomt of iets niet snapt dan kan je de student-assistenten(mij en Sam) ook altijd een berichtje sturen. Ga zo door!💪🏻
