### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by KaivWezel** [cmda-bt/pt-course-20-21#22]
# Package

S2FpdldlemVsCg==

## Name

Kai van Wezel

## Class

Tech1, 205

## Repo link

https://github.com/KaivWezel/Bloktech

## Summary

To start this week I repeated the workflow of GitHub and read articles about the documentation for GitHub and your projects. Then I started working with with the terminal and got introduced to bash. This was partly new for me and it was hard to really understand what was happening in the shell. Usually this is graphically designed to give the user a concept model but now it's just text. After I'd done the tutorial I started working on my concept. Thought of some ideas and wrote these out as in my wiki.

## Resources used

Besides the resources mentioned in the course, I used stackoverflow to find a way to use bash in the terminal in Visual Studio Code and to find some extra information about the commands used in bash.

## Any thoughts?

The tutorial in bash is useful but for the first time might be a bit too complicated. I think most of the course wil become clear in the process; "spelend leren".

**Comment by MarvinMichel** [comment]
Hi Kai,
De terminal kan soms een enge tool zijn, maar als de nieuwigheid er vanaf is wordt het inderdaad vanzelf een stuk duidelijker. Goed om te horen dat je zelf opzoek bent gegaan naar antwoorden op StackOverflow. Vergeet niet dat Sam en ik er ook nog zijn als je ergens niet uitkomt! We helpen je graag met extra uitleg, dat scheelt soms een hoop tijd😉
