### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Sophievanderburg** [cmda-bt/pt-course-20-21#23]
# Package

## Name

Sophie van der Burg

## Class

Tech2

## Repo link

https://github.com/Sophievanderburg/blok-tech

## Summary
First I read all the articles to try to understand git and Github. Then I created a repository for this block. After I finished this I read the articles about the terminal. And I did the tutorial which went surprisingly well. After that I started to work in my concept.

What I did for the concept:
First I decided for who I wanted to create a match-app for: For people who want to find other people to go to concerts/festivals with. Then I thought about what should be included in the app and made job stories for them. After I created the job stories, I chose which one I wanted to create in the first weeks of this block. For that job story I created a requirements list. And finally I created a wireframe with that requirements list.

## Resources used

You can find all the resources I used on this page: https://github.com/cmda-bt/pt-course-20-21/blob/main/week-1.md 

## Any thoughts?

At first I was a bit overwhelmed by all the information I had to take in. The articles talk about terms I have never heard about. Then it is difficult for me to understand the rest of the article. It takes a while before I understand what the article is actually about, but that is not surprising since I hear everything for the first time.

**Comment by Vuurvos1** [comment]
All the new information can be a bit overwhelming but once you start to use all the new concepts they should make more sense. The repository looks nice and clean although you do not need the `.ds_store` file and I would recommend adding it to your `.gitignore`. DS_STORE are Mac files that hold some drive information but aren't needed to make your app function, more info about them can be found [here](https://en.wikipedia.org/wiki/.DS_Store)
