### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Djescho** [cmda-bt/pt-course-20-21#26]
# Package

## Name

Djescho Mananga

## Class

TECH 2

## Repo link

[https://github.com/Djescho/Project-Tech]

## Summary

Deze week heb ik een concept bedacht voor de matching app. Het heet Music Match, een matching app waar gebruikers matchen op basis van muziek. Bij het concept heb ik 5 jobstorsies bedacht en daar één van uitgekozen en deze verder uitgewerkt. Bij deze uitwerking heb ik een feature list op gesteld zodat ik een overzicht heb van wat we uiteindelijk moeten gaan coderen.

## Resources used

Nog niks.

## Any thoughts?

Tot nu toe zeker te behappen! Ik kijk uit naar de komende weken.

**Comment by Vuurvos1** [comment]
Ik zie dat je al goed op weg bent alleen moet er nog wel het een en andergebeuren aan je repo, ik zie dat je een `main` en een `master` branch gebruikt en het meest hebt gedaan op de master alleen nu staat je `main` branch nog als default branch (dit kun je aanpassen in de installingen van de repo). Ook is je `.gitignore` nog leeg, hier zou ik je node modules map aan toevoegen en het `.ds_store` bestand omdat deze niet essentiel zijn voor het werken van je app, meer info over gitignore [hier](https://www.pluralsight.com/guides/how-to-use-gitignore-file)

Dus wat ik zou doen is kiezen welke branch je wilt blijven gebruiken, deze instellen als default en vervoglens alles overzetten van de andere branch naar je nieuwe default branch. Als je niet snapt wat ik hiermee bedoel schroom dan niet om mij (Sam de Kanter) een bericht te sturen op Teams of een van de andere student assistenten
