### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Kip-Hub** [cmda-bt/pt-course-20-21#35]
# Package

## Name

Daniel Kip

## Class

Tech 1a

## Repo link

https://github.com/Kip-Hub/matching-app

## Summary

Ik heb de artikelen die bij week 1 stonden doorgenomen, en de terminal opgave gemaakt met als resultaat de code: S2lwLUh1Ygo=
Vervolgens heb ik mijn concept beschreven in job stories, requirements en een eerste simpele wireframe

## Resources used

https://ss64.com/bash/ (om de verschillende commands te vinden voor de terminal opgave)

Verder heb ik voornamelijk de bronnen gebruikt die bij de opdracht stonden.

## Any thoughts?

De terminal opgave werkte eerst niet op Windows, maar gelukkig was er iemand op teams met hetzelfde probleem, en de oplossing ervan. De opgave zelf was niet erg lastig, en ik merk dat ik het gebruik van de terminal steeds beter begin te begrijpen.

**Comment by MarvinMichel** [comment]
Hi Daniel,
Goed dat je opzoek bent gegaan naar het antwoord. Als er in teams nog geen antwoord op je probleem is gegeven, kun je ook altijd een berichtje naar Sam of mij sturen!😊 Voeg nog even een `.gitignore` file aan je repo toe met `node_modules` daar aan toegevoegd, zodat je die niet meer naar git pusht. Je moet de directory dan nog wel verwijderen van GitHub.
