### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Adriaan350** [cmda-bt/pt-course-20-21#39]
# Package

## Name

Adriaan van der Heijden

## Class

205 - Tech 1

## Repo link

https://github.com/Adriaan350/blok-tech

## Summary
Als eerst heb ik de tutorial van de terminal gedaan en afgemaakt.

Mijn idee voor een matching app is teamgenoten vinden voor een sport die de gebruiker kiest. Een eventuele latere toevoeging is dat er ook wedstrijden gematched kunnen worden.

Mijn requirements list tot nu toe, dit wil ik nog wel aanvullen.
Een tinder soort match manier om de laatste persoon voor je team te vinden of invallers te vinden.
Een grote match door in 1 keer teams te vormen.
(extra) Wedstrijden zoeken. Andere teams kunnen andere teams vinden om tegen elkaar te gaan.

## Resources used

https://git-scm.com/book/en/v2
https://guides.github.com/activities/hello-world/
https://guides.github.com/features/wikis/#creating-your-wiki
https://gist.github.com/dandevri/9568a8dff8f572a0ea67627445aca5b2
Adobe XD

## Any thoughts?

Ik vind dat er bij de uitleg nog te veel gefocust wordt op Mac. Ik snap dat er misschien meer mensen op Mac zitten maar dan vind ik niet echt eerlijk dat het moeilijker wordt voor windows gebruikers. Ik heb bewust voor windows gekozen toen ik mijn 2500 euro laptop had gekocht.

**Comment by MarvinMichel** [comment]
Hi Adriaan!
De tutorials werken als een handvat, maar er wordt van je verwacht dat je zelf ook opzoek gaat naar oplossingen. Dit is ook een onderdeel van Development. Als je ergens echt niet uitkomt kun je altijd een vraag stellen in de channel of mij of Sam een berichtje sturen via teams. Vergeet ook niet om nog een License, readme en gitignore toe te voegen aan je repo.
