### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by LarsHVA** [cmda-bt/pt-course-20-21#40]
# Package

## Name

Lars Kamman

## Class

Tech 1B

## Repo link

https://github.com/LarsHVA/project-tech

## Summary

Ik heb in week 1:
Pro Git Online Book; 1.1, 1.2 & 1.3 snel doorgenomen. Hello world aangemaakt om te testen hoe pull en commit werkt op github. License en readme toegevoegt. Wiki aangemaakt voor tech met daarin tech 5 Job Stories, requirements list, wireframe, enz.. toegevoegt. Terminal tutorial gevolgt: Code tutorial: TGFyc0hWQQo=

Maar had ook https://www.base64encode.org/ kunnen gebruiken😂 toen ik de code aan het lezen was om te kijken hoe het werkte.  Had op zijn minst salt verwacht😉.

## Resources used

https://git-scm.com/book/en/v2
https://guides.github.com/activities/hello-world/
https://guides.github.com/features/wikis/#creating-your-wiki
https://gist.github.com/dandevri/9568a8dff8f572a0ea67627445aca5b2

## Any thoughts?

Maak ook de tutorials voor windows. moet nu zoveel zelf uitzoeken.

**Comment by MarvinMichel** [comment]
Hi Lars,
Wat jammer om te horen dat het gebrek aan Windows tutorials het moeilijker heeft gemaakt voor je. Het opzoeken van oplossingen is echter wel een competentie die van je gevraagd wordt als Developer. Verder staan Sam en ik ook klaar om te helpen, dus schroom niet ons een bericht te sturen voor hulp. Vergeet ook niet om de `node_modules` toe te voegen aan je `.gitognore`. Deze wil je niet op je repo hebben staan☺️

**Comment by LarsHVA** [comment]
Idd vergeten, dank je wel

https://stackoverflow.com/questions/50675829/remove-node-modules-from-git-in-vscode
Gebruikt om het weer van Github te verwijderen
