### ISSUE TITLE
Week 1  (verbeterde versie)

### ISSUE THREAD

**Issue by christiaanbraun** [cmda-bt/pt-course-20-21#41]
# Package

## Name

Christiaan Braun

## Class

tech2a

## Repo link
https://github.com/christiaanbraun/find_a_teammate

## Summary

I started working on my concept for the matching application and played around with the terminal

## Resources used

All the resources I used can be found here in my wiki under ["Week 1"](https://github.com/christiaanbraun/matching_application_bloktech/wiki)

## Any thoughts?

I had fun playing around with the terminal, the concept part was hard for me. Probably because I just want to code :(.

Y2hyaXN0aWFhbmJyYXVuCg==

**Comment by Vuurvos1** [comment]
Getting a good concept for you app can be hard but is essential to make a good product, for the rest of the feedback check your other week1 issue
