### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by babsluidinga** [cmda-bt/pt-course-20-21#42]
# Package

## Name

Babs Luidinga

## Class

TECH 1

## Repo link

https://github.com/babsluidinga/blok-tech

## Summary

Het bedenken van een concept voor de matching app, ik heb veel gebrainstormd en daar kwamen verschillende ideeën uit, je kan mijn voortgang vinden in mijn WIKI, daar zie je meteen wat ik heb gedaan voor dit vak deze week. Na het brainstormen ben ik gaan tekenen, niet dat dit echt iets voor mij is, maar ik wilde niet teveel druk leggen op het mooi maken van het ontwerp en me daar dan meteen op vastpinnen. Ik heb gekozen om het vinden van een match uit te werken, je kan matches zien op basis van hoeveel lievelingsboeken jullie met elkaar gemeen hebben en vervolgens kan je die match accepteren of niet. Als de andere persoon jou ook accepteert als match, komt diegene in je chat terecht!

## Resources used

In mijn wiki staat mijn bronvermelding, Nu staan ze nog per vak en per week, maar naarmate dit project vordert zal ik ook 1 groot bestand maken met al mijn brongebruik. 

## Any thoughts?

Vond het super leuk om te beginnen met iets anders dan coderen, we gaan toch de rest van de periode alleen maar programmeren, terwijl ik persoonlijk denk dat een goede developer ook de rest van het proces in acht moet nemen en niet alleen maar maakt wat van hem wordt gevraagd!

**Comment by MarvinMichel** [comment]
Hi Babs!
Je bent goed bezig geweest! Let alleen even op de files en directories die je upload. Voeg `node_modules` en `.DStore` nog even toe aan je `.gitignore`😊
