### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by DeefDeMeef** [cmda-bt/pt-course-20-21#45]
# Package

## Name

Davey Zaal

## Class

tech1 a - 212

## Repo link

https://github.com/DeefDeMeef/blok-tech

## Summary

Ik heb de tutorial.sh gedaan en een concept + job stories geschreven.

## Resources used

https://github.com/cmda-bt/pt-course-20-21/blob/main/week-1.md

## Any thoughts?

Het was vrij lastig om de tutorial.sh te laten werken in de terminal, ik kreeg het eerst niet voor elkaar omdat bash niet werkte maar uiteindelijk is het gelukt en was de gehele tutorial makkelijk te maken.

**Comment by MarvinMichel** [comment]
Hi Davey!
Je repo ziet er netjes uit met aparte directories voor ieder vak. Schrijf ook nog even een `.gitgnore` voor de files en directories die je niet wilt uploaden, zoals `node_modules` bij je back-end.
