### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by damian1997** [cmda-bt/pt-course-20-21#50]
# Package

## Name

Damian Veltkamp

## Class

Tech1 B

## Repo link

https://github.com/damian1997/Project-Tech

## Summary

During the first week I thought about what direction I wanted to take with my matching application and so I wrote 5 job stories.
Eventually I chose 1 job story and made a concise and clear requirements list for that particular job story

## Resources used
No resources used

## Any thoughts?
Nothing in particular

**Comment by MarvinMichel** [comment]
Hi Damian!
Je repo ziet er goed uit! Je mappen structuur is ontzettend netjes, net als je code. Ga zo door man🔥
