### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Mentalyzd** [cmda-bt/pt-course-20-21#54]
# Package

## Name
Christiaan Zandbergen

## Class
Tech 1 a (212)

## Repo link
https://github.com/Mentalyzd/Blok_Tech/wiki/Project-tech

## Summary
Concept uitleg met Job Stories en Wireframes.

## Resources used
https://github.com/cmda-bt/pt-course-20-21/blob/main/week-1.md

**Comment by MarvinMichel** [comment]
Hi Christiaan!
Ziet er goed uit. Ook een tof idee om uit te werken als match-app! Een verbetering om door te voeren in je repo: zet de `.node_modules` folder in je `.gitignore`. Die je wil je niet op je repo hebben staan😉
