### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by soofg** [cmda-bt/pt-course-20-21#65]
# Package
nodemon
express
ejs
clothes-by-weather

## Name
Sofya

## Class
211

## Repo link

https://github.com/soofg/Matching-App.git

## Summary

Ingelezen over markdown en geprobeerd om mijn files van mijn terminal te krijgen,  ik heb dit een aantal keer geprobeerd maar het is mij niet gelukt. Ik heb het handmatig gedaan, zoals ik eerder dit jaar bij FeD had geleerd.
En concept aangepast in mijn wiki!

## Any thoughts?

:)

**Comment by sjagoori** [comment]
Lekker bezig! Ik denk dat je met je _files_ de paginas in je wiki bedoelt; deze kan je binnen halen door `git clone https://github.com/soofg/Matching-App.wiki.git` in je terminal te tikken. De link kan je rechtsonder in je wiki terug vinden!
