### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by Kip-Hub** [cmda-bt/pt-course-20-21#66]
# Package

## Name

Daniel Kip

## Class

Tech 1a

## Repo link

https://github.com/Kip-Hub/matching-app

## Summary

Ik heb me verdiept in de stof over Markdown en Git. Vervolgens heb ik een eerste opzet gemaakt voor het README bestand van mijn repo. Tot slot ben ik gaan beunen met de templating engine EJS, en heb ik een begin-structuur gemaakt voor de pagina's/views van mijn feature. Deze is nog vrij beknopt, want ik merkte dat ik nog niet echt een goed beeld had van hoe ik mijn feature wil maken, en hoe deze er uit moet komen te zien. Dit vereist dus nog wat aandacht...

## Resources used

https://www.youtube.com/watch?v=VM-2xSaDxJc  

De resources die bij de opdrachten gegeven zijn

## Any thoughts?

Ik begrijp templating (denk ik) wel, maar vind het toepassen hiervan wel redelijk ingewikkeld, daarom vind ik de transitie van een simpele wireframe naar html pagina's (met gebruik van templating), nogal snel gaan.

**Comment by MarvinMichel** [comment]
Hi Daniel!

De opzet ziet er prima uit. De transitie kan inderdaad wat snel gaan, omdat het niet al te ingewikkelde stof is. Het is af en toe een beetje wennen, maar dat wordt vanzelf gewoonte. Je kunt altijd extra uitleg vragen bij de docenten of aan mij😉
