### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by maggness** [cmda-bt/pt-course-20-21#73]
# Package

## Name

Tim de Roller

## Class

Tech 2b

## Repo link

https://github.com/maggness/PT

## Summary

Ben deze week begonnen met het kijken naar andere README files en ben ook begonnen met die van mij. Nog wel beetje lastig om te bedenken wat er in moet omdat ik natuurlijk nog niet mega veel heb maar ik snap wel hoe ik zo'n file kan opbouwen. Ook had ik wat problemen met het aan de praat krijgen van mijn code maar dat is allemaal goed gekomen. Nog niet mega veel gedaan met de css en html maar deze week ga ik daar ff goed voor zitten.

## Resources used

Teams
https://github.com/GTAmodding/re3
https://github.com/bitcoin/bitcoin
Klasgenoten
https://www.youtube.com/watch?v=Je5w18nn-e8&list=PLu8EoSxDXHP7v7K5nZSMo9XWidbJ_Bns3&index=1&ab_channel=WesBos (video's over markdown)

## Any thoughts?

Ik had wel het gevoel dat het deze week veel was maar uiteindelijk wel te doen. Alleen probeerde ik bij de interactive markdown tutorials te komen maar ik kreeg een error page (https://github.com/cmda-bt/pt-course-20-21/blob/main/interactive)

**Comment by theonejonahgold** [comment]
Yo Tim!

Lekker bezig! Hier is wat feedback:

- Ik zie dat je veel commits hebt met de naam `Add files via upload`. Heb je git lokaal aan de praat gekregen? Het is wel de bedoeling dat je via je terminal of command prompt aan de slag gaat met git, zodat je niet iedere keer hoeft te wisselen van programma's maar gewoon lekker door kan werken.
- Je README is al aardig op weg, lekker bezig! Wat je eraan kan toevoegen zou bijvoorbeeld een lijst met features kunnen zijn die je toe wilt voegen, instructies voor hoe je aan de slag kan gaan met je project en/of eventueel een lijst met bronnen die je hebt gebruikt.
- Je wiki ziet er goed georganiseerd uit. Leuk dat je bent gaan klooien met je terminal en leuke berichtjes hebt toegevoegd. 😄
- Had je toevallig al een git strategie uitgekozen? Ik zie die nog niet in je wiki terugkomen.

Zo te zien ben je verder wel lekker op dreef. Ga vooral zo door! 👍🏻
