### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by jody29** [cmda-bt/pt-course-20-21#74]
# Package

## Name

Jody Lorist

## Class

Tech 2a

## Repo link

https://github.com/jody29/matching_feature

## Summary

Deze week ben ik vooral begonnen met schermen maken doormiddel van een templating engine. Ik heb gekozen om met EJS te gaan werken. Ook heb ik een git strategy gekozen. Ik heb ervoor gekozen om te gaan werken met een development branch. Ik zal dan elke keer eerst mijn code naar deze development branch pushen en dan elke week een mergen naar de main branch. Ik heb in mijn terminal `$ git checkout -b development` gedaan om de development branch aan te maken en hiernaar te switchen. Vervolgens heb ik een paar veranderingen gemaakt in mijn code om deze vervolgens naar de development branch te pushen. Hier begonnen te problemen voor mij. git add . en git commit -m 'commit message' lukten allemaal nog, maar bij git push gaf de terminal een foutmelding: ! [rejected]        development -> main (fetch first)
error: failed to push some refs to .... Toen ik git fetch deed was ik gelijk al mijn aanpassingen kwijt. Daarna heb ik weer git push geprobeerd en deed hij het weer niet. Vervolgens ben ik terug gegaan naar mijn main branch, heb daar een git fetch gedaan en vervolgens aanpassingen gedaan en daarna weer git push. Toen deed hij het wel. Alleen op mijn development branch doet hij het nog niet.

## Resources used

https://nvie.com/img/fb@2x.png
https://nvie.com/img/main-branches@2x.png
https://chris.beams.io/posts/git-commit/
https://confluence.atlassian.com/bitbucketserver/basic-git-commands-776639767.html_
https://nvie.com/posts/a-successful-git-branching-model/
https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging

## Any thoughts?

Eigenlijk ging bij mij gewoon alles goed tot ik met verschillende branches moest gaan werken. Dit heeft bij mij ook voor wat frustraties gezorgd.

**Comment by theonejonahgold** [comment]
Hey Jody!

Vervelend dat meerdere branches niet zijn gelukt man. Misschien helpt deze guide hier:

1. In je development branch, maak veranderingen aan
2. Commit deze veranderingen
3. Wanneer je pusht, typ je `git push -u origin {branchnaam}` waar `{branchnaam}` in dit geval `development` is.

Met `-u` zeg je tegen git dat de `development` branch lokaal gekoppeld is aan de `development` branch op GitHub. Nu hoef je niet iedere keer te zeggen naar welke branch je pusht. Ik heb namelijk het idee dat je `git push origin main` typte. Dat betekent dat je je development branch naar de main branch op GitHub probeert te pushen, wat natuurlijk niet gaat. Onthou die `-u` dus goed, want dat kan je bij elke branch doen, waarna je alleen nog maar `git push` hoeft te typen als je in die branch zit.

Hier heb je nog wat feedback:

- Goeie README, duidelijke instructies voor installatie! Misschien nog een idee om een korte uitleg van het project bovenaan te schrijven, en eventueel wat features van de app in een lijst te zetten.
- Ik kan niet bij je Job Stories of Requirements List pagina komen. Je hebt de edit link in de inhoudsopgave gezet, in plaats van de pagina link. Git strategy gaat wel goed, en die ziet er ook erg netjes uit!
- Goeie start aan het uitwerken van je pagina's. Design ziet er gelikt uit. 😊

Je bent al goed op weg. Ga zo door! 💪🏻

**Comment by jody29** [comment]
Heel erg bedankt voor de uitleg, het is me uiteindelijk gelukt.

Ik heb de linkjes naar zowel de job stories als de requirements list aangepast. Deze zouden nu dus te zien moeten zijn. Anders staan de job stories en de requirements list ook bij pages > Project tech week 1.
