### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by DeefDeMeef** [cmda-bt/pt-course-20-21#77]
# Package

## Name

Davey Zaal

## Class

Tech 1a - 212

## Repo link

https://github.com/DeefDeMeef/blok-tech

## Summary

Ik heb de readme aangepast zodat het bij dit project past. Verder snap ik nog niet zo goed hoe het nou werkt met de HTML pagina's. We moeten een app uiteindelijk gaan bundelen met een groepje maar stel alle 4 de mensen hebben bijvoorbeeld een login gemaakt dan moet je aan het eind opeens heel veel werk gaan verzetten? Ik snap niet zo goed wat ik hiermee moet doen eigenlijk. Om deze reden heb ik nog geen HTML gemaakt maar dat haal ik in zodra ik weet of het goed gaat of niet. 

## Resources used

Ik heb de readme van week 2 gebruikt en heb in me wiki veel verschillende markdown gebruikt om er mee te oefenen. 

## Any thoughts?

Het is best simpel eigenlijk. Ik ben ook nergens tegen aan gelopen.

**Comment by MarvinMichel** [comment]
Hi Davey!
In principe is het de bedoeling dat je zo ver mogelijk komt met de applicatie, maar het hoeft niet een volledig werkende app te worden. Je kiest een aantal functionaliteiten en die werk je zo goed mogelijk uit. Het is wellicht leuker om een team te vormen met mensen die iets anders gedaan hebben dan jij, maar dat is niet persé een vereiste. Als je het blok gemakkelijk vind gaan, zoek dan zelf ook naar uitdaging. Kijk of je buiten de lesstof om nog toepasbare dingen kan leren. Duik bijvoorbeeld in Design Systems of best practices om je code zo netjes mogelijk te maken.
