### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by Djescho** [cmda-bt/pt-course-20-21#78]
# Package

## Name

Djescho Mananga

## Class

TECH2

## Repo link

https://github.com/Djescho/ProjectTech

## Summary

Deze week ben ik hard aan de slag geweest. Als eerst kreeg ik mijn git via de terminal niet meer werkende, dus dat was al een mooi begin. Na heel veel gegoogle en gevraag ben ik opnieuw begonnen met een nieuwe repository. Nu git werkte en ik er een beetje de vingers in kreeg ben ik hard aan de slag gegaan met het opnieuw bouwen van mijn applicatie. De app bevat 3 html pagina's (waarvan 2 werkende zijn) met css. Ik heb me er op gefocust om deze week de API aan de praat te krijgen en ook dit is met gelukt. Nu nog de brug slaan tussen html en de backend om daadwerkelijk input Vannuit een formulier te krijgen.

## Resources used

https://www.youtube.com/watch?v=z8m_Vy_9FIs&t=78s
https://www.youtube.com/watch?v=NxVCq4p0Kb0&t=75s
https://www.youtube.com/watch?v=0tOgMSEPFRs
https://www.youtube.com/watch?v=m3YpkqhHKdk&t=221s
https://www.youtube.com/watch?v=EQWyWQhphGw&t=96s
https://www.youtube.com/watch?v=shSB9BbK1gU
https://www.w3docs.com/snippets/javascript/how-to-loop-through-an-array-in-javascript.html
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods
https://developer.mozilla.org/en-US/docs/Web/HTTP
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API
https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_forms_through_JavaScript
https://www.w3schools.com/html/html_forms.asp
https://stackoverflow.com/questions/24338016/capture-html-form-data-with-external-js-file
https://stackoverflow.com/questions/63576988/how-to-use-formdata-in-node-js-without-browser
https://www.codota.com/code/javascript/modules/form-data

## Any thoughts?

Het was veel werk (vooral het dingen opzoeken) maar ik vond het zeker wel te doen. Het goed Googlen blijkt soms nog wel eens lastig.

**Comment by Vuurvos1** [comment]
Goed kunnen Googlen is een kunst op zich, maar wel een essentieel deel van het leven van een developer en heeft dus oefening nodig. Je bent al goed bezig met EJS maar ik mis nog wel erg veel documentatie in de wiki en in de readme, in de wiki heb je al wel alle paginas gemaakt maar deze zijn nog leeg (staan nog in je oude repo?) ga dit doen, hier wordt je uiteindelijk op beoordeeld. De readme is ook nog erg leeg, mischien kun je uit mijn team repo van vorig jaar wat inspiratie op doen: https://github.com/vuurvos1/projectTechGroup . Documentatie is mischien niet het leukste maar wel essentieel als je de vakken wilt halen
