### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by dannyfrelink** [cmda-bt/pt-course-20-21#79]
# Package

## Name

Danny Frelink

## Class

Tech 3, 211

## Repo link

https://github.com/dannyfrelink/Blok-Tech

## Summary

Gewerkt aan het maken van het huiswerk door alle stapjes te doorlopen. Verder heb ik ook nieuwe wireframes gemaakt om mijn concept beter weer te geven.

## Resources used

De bronnen gegeven op de pt-course repo en Illustrator voor het maken van mijn wireframes.

## Any thoughts?

Ik vond het huiswerk wel goed te doen, maar wel nog lastig of mijn concept niet te moeilijk zou zijn om te realiseren.

**Comment by sjagoori** [comment]
Gaaf concept! Het is zeker te doen. Als de job story veranderd naar "_Wanneer ik een profiel registreer op de app, wil ik mijn reizen en goals opgeven, zodat ik sneller match met soortgelijke reisliefhebbers_". Dan zou je op basis van de voorkeuren en/of interesses van de profielen matches kunnen maken.
