### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by LarsHVA** [cmda-bt/pt-course-20-21#82]
# Package

## Name

Lars Kamman

## Class

Tech 1 b

## Repo link

https://github.com/LarsHVA/project-tech

## Summary

Mastering Markdown snel door heen gegaan
readme.md aangepast(nog niet gecommit)
katacoda doorgenomen
view map gemaakt en ejs geinstaleerd en 1 template gemaakt (nog niet gecommit)

## Resources used

https://www.katacoda.com/courses/git
https://www.youtube.com/watch?v=Je5w18nn-e8&list=PLu8EoSxDXHP7v7K5nZSMo9XWidbJ_Bns3

## Any thoughts?

/

**Comment by MarvinMichel** [comment]
Hi Lars!

Het is verstandig om toch alle veranderingen te comitten naar GitHub. Al doe je maar iets kleins. De kracht van Git ligt juist in de version control. Als je iets breekt in je code kun je dan altijd terug naar een vorige versie. Hoe meer je commit, hoe meer backups je hebt van je code. Blijf dat dus vooral doen. Als je vragen hebt over Git of GitHub dan help ik je daar graag mee!😊
