### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by Sophievanderburg** [cmda-bt/pt-course-20-21#88]
# Package

## Name

Sophie van der Burg

## Class

Tech 2b

## Repo link

https://github.com/Sophievanderburg

## Summary

Als eerste heb ik met MarkDown gewerkt. Hier was ik al een beetje bekend mee door vorig jaar. Ook zijn er veel cheatsheets op internet te vinden, dus dat helpt ook. :)

Daarna ben ik bezig geweest met Git en de CLI. Ik vind de terminal nog af en toe een beetje spannend, maar ik word er steeds een beetje handiger in. Het comitten en pushen naar Github gaat nu zelfs bijna vanzelf.

Ik ben wel begonnen aan de HTML/css, maar daar ben ik nog niet heel ver mee gekomen doordat ik erg vastliep met het huiswerk van backend. Ik wilde eerst de templating engine regelen en dan gelijk in ejs gaan bouwen.

## Resources used

Bronnen die ik heb gebruikt staan op: https://github.com/cmda-bt/pt-course-20-21/blob/main/week-2.md

## Any thoughts?

Het huiswerk van deze week was niet heel lastig. Ik vond het wel moeilijk om te bedenken wat ik precies in mijn readme moest zetten, omdat we nog niet zo ver zijn met het uitwerken.

**Comment by Vuurvos1** [comment]
Goed om te hooren dat het werken met git al soepel gaat, vergeet niet vaak en consistent te comitten. De readme voor het project is nog wat kort, je zou wat inspiratie op kunnen doen uit [dit project](https://github.com/vuurvos1/projectTechGroup) van mij, voor sommige van de meer "fancy" dingen met markdown zou je [dit artikel](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) nog een door kunnen lezen. En vergeet je bronnen niet te noteren
