### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by deinca** [cmda-bt/pt-course-20-21#9]
# Package

## Name

Deiver Zamora Cortez

## Class

Tech 1 - b
## Repo link

[Block Tech 21](https://github.com/deinca/block-tech-21)

## Summary

Ik heb het volgende gedaan:
Een repo aangemaakt
Github aantekening van mijn research
Concept bedacht met Job Stories, URL's en wireframes
En aan mijn wiki gewerkt.

## Resources used
* [hello-word getting-started github](https://guides.github.com/activities/hello-world/)
* [Documentation github](https://guides.github.com/features/wikis/#creating-your-wiki)
* [Github git-flow uitleg](https://guides.github.com/introduction/flow/)

## Any thoughts?

De lessen zijn veel beter dan twee geleden ik liep nog ergens tegen met github door pull  request error maar dat heb ik gelukkig opgelost door een file uit mijn locale repo eruit te halen en te fetchen en dan dan de files te replacen en weer gepusht. 👍 

Wat misschien graag zou willen weten of mijn concept wel realistisch is en of ik niet te veel of te moeilijk denk. Graag zou ik willen weten wat jullie erover denken 😄.

Dankjewel voor het lezen 🤓

**Comment by MarvinMichel** [comment]
Hi Deiver!
Goed om te horen! Voor zover ik zie denk je zeker niet te moeilijk. Je concept is goed te realiseren. Misschien is het zelfs leuk om meerdere games te kunnen kiezen i.p.v. één game? Je repo ziet er voor de rest netjes uit💪🏻

**Comment by deinca** [comment]
Hey Marvin, dankjewel voor je reactie. 
Goed punt als het mij lukt ga ik je tip doorvoeren in mijn applicatie 😆!
