### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by mandemt** [cmda-bt/pt-course-20-21#92]
# Package

## Name

Tom Mandemaker

## Class

209

## Repo link

[Repository](https://github.com/mandemt/techblok)

## Summary

Artikelen, job stories, alles gemaakt en toegevoegd aan de wiki.

## Resources used

https://git-scm.com/book/en/v2
https://opensource.guide/starting-a-project/
https://react.design/terminal
https://github.com/philipcdavis/laurelin

## Any thoughts?
Ik wil graag weten voor welk device de feature wordt verwacht.

**Comment by ivo-online** [comment]
Qua device mag je zelf kiezen waar je je feature primair voor gaat ontwerpen. Als je kijkt naar je feature, in wat voor context en op wat voor apparaat zouden je gebruikers die dan het meest waarschijnlijk gaan gebruiken?
